version: "3"
services:
  app:
    container_name: docker-node-mongo
    restart: always
    build: .
    ports:
      - "3001:3001"
    external_links:
      - mongo
  mongo:
    container_name: mongo
    image: larsla/mongo-armv7l
    ports:
      - "27017:27017"
