version: "3"
services:
  app:
    container_name: budget-tracker
    restart: always
    build: . # build from the docker file from '.'
    ports:
      - "3001:3001"
    links:
      - mongo
    networks:
      - webappnetwork
  mongo:
    container_name: mongo
    image: nonoroazoro/rpi-mongo
    ports:
      - "27016:27017"
    networks:
      - webappnetwork
networks:
  webappnetwork:
    driver: bridge
