version: "3"
services:
  app:
    container_name: budget-tracker
    restart: always
    build: . # build from the docker file from '.'
    ports:
      - "3001:3001"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: nonoroazoro/rpi-mongo
    ports:
      - "27016:27016"
    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/configdb

volumes:
  mongodb:
  mongodb_config:
